-- 사원아이디, 이름, 직종아이디, 부서아이디, 부서명, 급여, 커미션, 급여등급, 연봉
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY, E.COMMISSION_PCT, S.GRADE, 
       E.SALARY*12 + E.SALARY*NVL(E.COMMISSION_PCT, 0)*12 ANNUAL_SALARY
FROM EMPLOYEES E, DEPARTMENTS D, SALARY_GRADE S
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY;

-- 전달받은 사원아이디에 해당하는 사원의 사원아이디, 이름, 직종아이디, 부서아이디, 부서명, 급여, 커미션, 급여등급, 연봉
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY, E.COMMISSION_PCT, S.GRADE, 
       E.SALARY*12 + E.SALARY*NVL(E.COMMISSION_PCT, 0)*12 ANNUAL_SALARY
FROM EMPLOYEES E, DEPARTMENTS D, SALARY_GRADE S
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY
AND E.EMPLOYEE_ID = 100;

-- 전달받은 부서아이디에 소속되어 있는 사원의 사원아이디, 이름, 직종아이디, 부서아이디, 부서명, 급여, 커미션, 급여등급, 연봉
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY, E.COMMISSION_PCT, S.GRADE, 
       E.SALARY*12 + E.SALARY*NVL(E.COMMISSION_PCT, 0)*12 ANNUAL_SALARY
FROM EMPLOYEES E, DEPARTMENTS D, SALARY_GRADE S
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY
AND E.DEPARTMENT_ID = 60;

-- 전달받은 급여등급에 해당하는 사원의 사원아이디, 이름, 직종아이디, 부서아이디, 부서명, 급여, 커미션, 급여등급, 연봉
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY, E.COMMISSION_PCT, S.GRADE, 
       E.SALARY*12 + E.SALARY*NVL(E.COMMISSION_PCT, 0)*12 ANNUAL_SALARY
FROM EMPLOYEES E, DEPARTMENTS D, SALARY_GRADE S
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY
AND S.GRADE = 'E';

-- 전달받은 최소급여, 최대급여 범위에 속하는 사원의 사원아이디, 이름, 직종아이디, 부서아이디, 부서명, 급여, 커미션, 급여등급, 연봉
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY, E.COMMISSION_PCT, S.GRADE, 
       E.SALARY*12 + E.SALARY*NVL(E.COMMISSION_PCT, 0)*12 ANNUAL_SALARY
FROM EMPLOYEES E, DEPARTMENTS D, SALARY_GRADE S
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY
AND E.SALARY >= 3000 AND E.SALARY <= 5000;
